version: '3.8'

services:
  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    hostname: kafka
    environment:
      # KRaft ÏÑ§Ï†ï
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'   # ÏÇ¨Ïö©Ïûê ÏßÄÏ†ï ID Ïú†ÏßÄ

      # Î¶¨Ïä§ÎÑà ÏÑ§Ï†ï (ÎÇ¥Î∂Ä ÌÜµÏã†Ïö©)
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'

      # Îç∞Ïù¥ÌÑ∞ Í≤ΩÎ°ú
      KAFKA_LOG_DIRS: '/var/lib/kafka/data'

      # Î∏åÎ°úÏª§ ÏÑ§Ï†ï
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

      KAFKA_HEAP_OPTS: "-Xmx400m -Xms400m"

    # Ìè¨Îß∑ÌåÖ Ïä§ÌÅ¨Î¶ΩÌä∏ Ï∂îÍ∞Ä
    # meta.propertiesÍ∞Ä ÏóÜÏúºÎ©¥ ÏßÄÏ†ïÎêú CLUSTER_IDÎ°ú Ìè¨Îß∑ÌåÖ ÌõÑ Ïã§Ìñâ
    command: >
      bash -c '
      if [ ! -f /var/lib/kafka/data/meta.properties ]; then
        echo "‚è≥ KRaft Storage Formatting (ID: $KAFKA_CLUSTER_ID)..."
        kafka-storage format -t $KAFKA_CLUSTER_ID -c /etc/kafka/kafka.properties
      fi
      echo "üöÄ Starting Kafka..."
      /etc/confluent/docker/run'

    volumes:
      - ./kafka-data:/var/lib/kafka/data

    networks:
      - app-network
    restart: always

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: prod-kraft
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    networks:
      - app-network
    depends_on:
      - kafka
    restart: always

  kafka-exporter:
    image: danielqsj/kafka-exporter
    container_name: kafka-exporter
    command: ["--kafka.server=kafka:29092"]
    ports:
      - "9308:9308"
    networks:
      - app-network
    depends_on:
      - kafka
    restart: always

networks:
  app-network:
    external: true